### PR TITLE
Added fix for network next_available_ip with a supporting test case.

### PR DESCRIPTION
**Pull request by prabhu-das**
Please review and merge.

### CODE REVIEW

**Comment by prabhu-das** [comment]
Thanks for the quick review :+1:  . Let me explain my issue:
When I call the code  
JSON.parse(connection.post(resource_uri + "/#{network}?_function=next_available_ip", post_body).body)["ips"]

I get : ["10.10.70.11"]
But when I call with the old code
JSON.parse(connection.post(resource_uri + "?_function=next_available_ip", post_body).body)["ips"]

I get: 
Infoblox::Error: Error: 400 { "Error": "AdmConProtoError: Invalid reference: ",
  "code": "Client.Ibap.Proto",
  "text": "Invalid reference: "
}

So if I just print the string part ( resource_uri + "?_function=next_available_ip" ) , It returns me 
=> "/wapi/v1.0/network?_function=next_available_ip") , where there is no network provided. So I added the #{network} explicitly, to get the string something like this :  "/wapi/v1.0/network/ZG5zLm5ldHdvcmskMTAuMTAuNzAuMC8yNC8w:10.10.70.0/24/default?_function=next_available_ip"

If you are getting ips without providing #{network}, It must be that the network is there in the resource_uri, part. Can you please provide your resource_uri ? I mean if it contains the network ref there?

I referred this link too: https://community.infoblox.com/forum/ddi/definitive-list-rest-examples,
Please help me with any better API docs if you have.

**Comment by unclebilly** [comment]
According to the docs you linked, you need the ref to do that function.  The ref is loaded when you query the API for the network object first.  This code works for me (using the current version): 
```
connection = Infoblox::Connection.new(username: '...', 
                                      password: '...', 
                                      host:     '...', 
                                      logger:   Logger.new(STDOUT))
network    = Infoblox::Network.find(connection, 
                                   network: '10.21.0.0/24').first
puts network.next_available_ip

```
Is there some reason you can't do it this way?

**Comment by prabhu-das** [comment]
Thanks @unclebilly , Infoblox::Network.find approach worked. You can close the PR, or if you want I can revert the change and keep just the network_spec.rb after updating it.

**Comment by unclebilly** [comment]
OK @prabhu-das - I'm thinking this is a feature that can be documented better. I'll update the README with an example.

**Pull request closed without merging**
