### PR TITLE
Added implementation for range with a test case.

### PR DESCRIPTION
**Pull request by prabhu-das**
Please review and merge if there are no issues.

### CODE REVIEW

**Comment by unclebilly** [comment]
@prabhu-das  Thank you for your contribution!

**Comment by unclebilly** [comment]
This has been pushed to Rubygems.org in 0.2.19.

**Comment by prabhu-das** [comment]
Thanks @unclebilly for merging the changes. I wanted to know, is there any specific version of the WAPI that you use to test the changes, And the vNIOS version that you use ?

I test the changes with WAPI 1.6 and 2.0 with vNIOS 7.2.x. There are few changes that doesn't work with the default WAPI version 1.0, that we have in this gem. 
module Infoblox
  WAPI_VERSION = ENV['WAPI_VERSION'] || '1.0'

Can we set the baseline as 1.2 or above, in fact 1.6 which is more stable and widely used than previous versions. The fixedaddress doesn't work with 1.0, So the client has to provide his WAPI version to make it work. 

Similarly the extensible_attributes has been changed to extattrs from 1.2 onwards till latest version.
$ curl -k -u admin:infoblox -H "Content-Type: application/json" -X GET https://10.10.70.10/wapi/v1.0/record:host?_return_fields=extensible_attributes
[]

$ curl -k -u admin:infoblox -H "Content-Type: application/json" -X GET https://10.10.70.10/wapi/v2.0/record:host?_return_fields=extensible_attributes
{ "Error": "AdmConProtoError: Unknown argument/field: 'extensible_attributes'",
  "code": "Client.Ibap.Proto",
  "text": "Unknown argument/field: 'extensible_attributes'" 
}

Please let me know your thoughts on the above.

**Comment by prabhu-das** [comment]
For EX: to make the gem work with WAPI version >= 1.2, we need to change the below
class Network < Resource
    remote_attr_accessor :network, :extensible_attributes

to 
class Network < Resource
    remote_attr_accessor :network, :extattrs

same goes with other classes too. Can you please validate me if I am wrong.

**Comment by unclebilly** [comment]
@prabhu-das I would entertain a merge request to add that extensible attribute change.   We are using WAPI v2.0 - but the API is backwards-compatible and we're still sending over v1.0 API requests.  One of the contributors to this gem (@sandlerr) added a feature to make the WAPI version configurable (by setting `ENV['WAPI_VERSION']`). That would be a good place to start - checking the value of `Infoblox::WAPI_VERSION`.

**Comment by sandlerr** [comment]
Does that mean there was a breaking change between WAPI versions? @epssy this would invalidate our assumption, it might be better to put in guards or conditionals after all.

**Comment by unclebilly** [comment]
@sandlerr I think you are correct - we would have to wrap `extensible_attributes` and `extattrs` with a conditional version check in this case.  I wonder if there are any other incompatibilities.

**Comment by epssy** [comment]
That was the only breaking change I found using the set of resources explicitly supported by this library when testing against WAPI 1.0, 1.1, 1.2, and 1.4.2.  I do vaguely remember there being a breaking change being talked about on the forums for the grid object but I cannot find that again, so maybe a faulty memory.

**Comment by unclebilly** [comment]
@prabhu-das  - In the case of `FixedAddress` and the numerous other objects present only in versions later than 1.0, we have a several options that I can think of:

1. Only define those resources when the `Infoblox::WAPI_VERSION` is correct (wrap the entire class definition with a condition check)
2. Raise an exception when the resources are used with the incorrect `Infoblox::WAPI_VERSION` (raised in the constructor & class methods)
3. Allow the client to use any object with any `Infoblox::WAPI_VERSION` and let the Infoblox server figure it out.

I prefer the third option, as it is less work on the client side and less prone to becoming out-of-date.  We can always provide or defer to the WAPI documentation for consumers to figure out what is supported in their version.   What do you think?

**Pull request merged**
