### PR TITLE
Change Ipv4address behaviour to use remote_attr_accessor

### PR DESCRIPTION
**Pull request by Klaas-**
I'm not sure if you made this on purpose but I would like to return values by default

### CODE REVIEW

**Comment by unclebilly** [comment]
According to the WAPI docs, every field on Ipv4address is read-only (except for `extattrs`).  The `remote_attr_accessor` is used to define fields that are read/write... Are you using this object to modify those fields somehow?

**Comment by Klaas-** [comment]
no, I just want the object to return them by default - at the moment if you for example search for ipv4addresses in a network it won't return any information :)
Infoblox::Ipv4address.find(connection, {"network" => "192.168.0.0/24"}).first.ip_address
=> "192.168.0.0"
but if I only use attr_accessor it will show
Infoblox::Ipv4address.find(connection, {"network" => "192.168.0.0/24"}).first.ip_address
=> nil
what would be the correct way to implement it to return the information I'd like?

**Comment by unclebilly** [comment]
I see the issue now.  I'm going to add a `remote_attr_reader` class method to address this.

**Comment by unclebilly** [comment]
@Klaas- let me know if that works for you!  I'd like to push out a new gem version.

**Comment by Klaas-** [comment]
I get an error when trying:
Infoblox::Ipv4address.find(connection, {"network" => "192.168.152.0/21", "_max_results" => "1"})
it does seem to work without max results
Infoblox::Ipv4address.find(connection, {"network" => "192.168.152.0/21"})
Infoblox::Error: Error: 400 { "Error": "AdmConProtoError: Result set too large (> 1000)",
  "code": "Client.Ibap.Proto",
  "text": "Result set too large (> 1000)"
}

**Comment by Klaas-** [comment]
to clarify - I just copied the latest git state to gem dir :)

**Comment by unclebilly** [comment]
@Klaas- Sorry about that.  I pushed up another commit that should address that issue.  Let me know how it works for you!

**Comment by Klaas-** [comment]
Hi @unclebilly , that works for me -- thanks a lot! :)

Greetings
Klaas

**Comment by unclebilly** [comment]
@Klaas- I pushed up gem version 0.3.3 with this change.  Thanks, and let me know if there's anything else I can do to help.  I know you are working on Foreman / Infoblox compatibility, which I'm particularly interested in! :+1:

**Comment by Klaas-** [comment]
@unclebilly you can have a look at my first try, but keep in mind usually I'm not a ruby coder :D I'd be thankeful for any feedback - especially when I do dumb stuff that ruby could do way easier :)
https://github.com/Klaas-/smart-proxy/tree/infoblox_support
& https://github.com/Klaas-/smart-proxy/tree/loadRecord for a small change to the dhcp_api to speed up lookup of single records :)

**Comment by unclebilly** [comment]
@Klaas- have you submitted a PR to Foreman yet?  I will comment on if if you do.

**Comment by Klaas-** [comment]
the dhcp proxy is currently ruby 1.8.7, that won't work with the infoblox gem so it won't really get picked up until either the dhcp proxy gets more modular or they move that requirement
http://projects.theforeman.org/issues/8046 is the issue, I'm waiting to hear about feedback to code in general.
for now I'm satisfied myself with running it on ruby193 :) the loadrecord tree should be picked up after testing by foreman team

**Comment by unclebilly** [comment]
Would it help if I made this gem compatible with ruby 1.8.7?  It probably wouldn't be too difficult.

**Comment by Klaas-** [comment]
well then I could try to get it into the current dhcp proxy, sure its worth a try :)

**Comment by unclebilly** [comment]
@Klaas- I just pushed out gem version 0.4.0 with Ruby 1.8.7 compatibility.

**Pull request closed without merging**
